# Generated by Django 3.1 on 2021-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_project',
            field=models.BooleanField(default=True),
        ),
    ]
